apiVersion: redis.kun/v1alpha1
kind: DistributedRedisCluster
metadata:
  annotations:
    # if your operator run as cluster-scoped, add this annotations
    {{- if .Values.redis.operatorClusterScoped }}
    redis.kun/scope: cluster-scoped
    {{- end }}
  name: {{ include "redis-cluster.fullname" .}}
spec:
  image: {{ .Values.images.redis.repository }}{{.Values.images.redis.name }}:{{ .Values.images.redis.tag }}
  masterSize: {{ .Values.redis.masterSize }}
  clusterReplicas: {{ .Values.redis.replicas }}
  {{- if .Values.redis.storage.enabled }}
  storage:
  {{ toYaml .Values.redis.storage | indent 4 }}
  {{- end }}
  {{- if .Values.redis.serviceName.enabled }}
  serviceName: {{ .Values.redis.serviceName.value }}
  {{- end }}
  {{- if .Values.redis.password.enabled }}
  passwordSecret:
    name: {{ include "redis-cluster.fullname" .}}
  {{- end }}
  resources:
    {{ toYaml .Values.redis.config | indent 4 }}
  {{- if .Values.redis.monitor.enabled }}
  monitor:
    image: {{ .Values.images.monitor.repository }}{{.Values.images.monitor.name }}:{{ .Values.images.monitor.tag }}
  {{- end }}
  config:
    {{ toYaml .Values.redis.config | indent 4 }}


  securityContext:
    {{- toYaml .Values.redis.securityContext | indent 4 }}
  containerSecurityContext:
    {{- toYaml .Values.redis.securityContext | indent 4 }}

