apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "redis-cluster-operator.fullname" .}}
spec:
  replicas: {{ .Values.operator.replicas }}
  selector:
    matchLabels:
      name:  {{ include "redis-cluster-operator.fullname" .}}
  template:
    metadata:
      labels:
        name:  {{ include "redis-cluster-operator.fullname" .}}
    spec:
      imagePullSecrets:
        {{- toYaml .Values.operator.imagePullSecret | nindent 8 }}
      serviceAccountName:  {{ include "redis-cluster-operator.fullname" .}}
      securityContext:
        {{- .Values.operator.podsecurityContext | toYaml | nindent 8 }}
      containers:
        - name: {{ .Values.operator.name }}
          # Replace this with the built image name
          image: {{ .Values.operator.image_source }}:{{ .Values.operator.image_tag }}
          securityContext:
            {{- .Values.operator.containersecurityContext | toYaml | nindent 12 }}
          command:
          - redis-cluster-operator
          args:
          - --rename-command-path=/etc/redisconf
          - --rename-command-file=redis.conf
          imagePullPolicy: {{ .Values.operator.imagePullPolicy }}
          resources:
            {{- .Values.operator.resources | toYaml | nindent 12 }}
          env:
            - name: WATCH_NAMESPACE
              value: {{ $.Release.Namespace | quote }}
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: {{ include "redis-cluster-operator.fullname" . | quote }}
          volumeMounts:
            - name: redisconf
              mountPath: /etc/redisconf
      volumes:
        - name: redisconf
          configMap:
            name:  {{ include "redis-cluster-operator.fullname" .}}-admin

---
apiVersion: v1
kind: ConfigMap
metadata:
  name:  {{ include "redis-cluster-operator.fullname" .}}-admin
data:
  redis.conf: |- 
    {{- .Values.data.redis_conf | nindent 4 }}
