{{- if .Values.operator.clusterScoped }}
kind: ClusterRoleBinding
{{- else }}
kind: RoleBinding
{{- end }}
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name:  {{ include "redis-cluster-operator.fullname" .}}
subjects:
- kind: ServiceAccount
  name:  {{ include "redis-cluster-operator.fullname" .}}
  namespace: {{ $.Release.Namespace }}
roleRef:
  {{- if .Values.operator.clusterScoped }}
  kind: ClusterRole
  {{- else }}
  kind: Role
  {{- end }}
  name:  {{ include "redis-cluster-operator.fullname" .}}
  apiGroup: rbac.authorization.k8s.io
