{{- if .Values.operator.clusterScoped }}
kind: ClusterRoleBinding
{{- else }}
kind: RoleBinding
{{- end }}
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: redis-cluster-operator
subjects:
- kind: ServiceAccount
  name: redis-cluster-operator
  namespace: {{ $.Release.Namespace }}
roleRef:
  {{- if .Values.operator.clusterScoped }}
  kind: ClusterRole
  {{- else }}
  kind: Role
  {{- end }}
  name: redis-cluster-operator
  apiGroup: rbac.authorization.k8s.io
