apiVersion: redis.kun/v1alpha1
kind: DistributedRedisCluster
metadata:
  annotations:
    # if your operator run as cluster-scoped, add this annotations
    {{- if .Values.redis.operatorClusterScoped }}
    {{- with (index .Values "redis-cluster-operator") }}
    {{- if (eq (len .operator.namespace) 0) }}
    redis.kun/scope: cluster-scoped
    {{- end }}
    {{- end }}
    {{- end }}
  name: {{ include "empirix-redis-cluster.fullname" .}}
spec:
  image: {{ .Values.images.redis.repository }}{{.Values.images.redis.name }}:{{ .Values.images.redis.tag }}
  masterSize: {{ .Values.redis.masterSize }}
  clusterReplicas: {{ .Values.redis.replicas }}
  {{- if .Values.redis.storage.enabled }}
  storage:
    {{- toYaml .Values.redis.storage | nindent 4 }}
  {{- end }}
  {{- if .Values.redis.serviceName.enabled }}
  serviceName: {{ .Values.redis.serviceName.value }}
  {{- end }}
  {{- if .Values.redis.password.enabled }}
  passwordSecret:
    name: {{ include "empirix-redis-cluster.fullname" .}}
  {{- end }}
  resources:
    {{- toYaml .Values.redis.config | nindent 4 }}
  {{- if .Values.redis.monitor.enabled }}
  monitor:
    image: {{ .Values.images.monitor.repository }}{{.Values.images.monitor.name }}:{{ .Values.images.monitor.tag }}
  {{- end }}
  config:
    {{- toYaml .Values.redis.config | nindent 4 }}
  requiredAntiAffinity: {{ .Values.redis.requiredAntiAffinity }}
  annotations:
    {{- toYaml .Values.redis.annotations | nindent 4 }}
  env:
    {{- toYaml .Values.redis.envVars | nindent 4 }}
  securityContext:
    {{- toYaml .Values.redis.securityContext | nindent 4 }}
  containerSecurityContext:
    {{- toYaml .Values.redis.securityContext | nindent 4 }}
  toleRations:
    {{- toYaml .Values.redis.tolerations | nindent 4 }}
  nodeSelector:
    {{- toYaml .Values.redis.nodeSelector | nindent 4 }}
  affinity:
    {{- toYaml .Values.redis.affinity | nindent 4 }}
  init:
    {{- toYaml .Values.redis.initContainer | nindent 4 }}
