{{- if .Values.redis.password.enabled }}
apiVersion: v1
kind: Secret
metadata:
  annotations:
    # if your operator run as cluster-scoped, add this annotations
    redis.kun/scope: cluster-scoped
  name: {{ include "empirix-redis-cluster.fullname" .}}
type: Opaque
data:
  password: {{ .Values.redis.password.value}}
{{- end }}
