operator:
  backup_enabled: "false"
  name: "redis-cluster-operator"
  replicas: 1
  clusterScoped: true
  image_source: "mttbadiali/redis-cluster-operator"
  image_tag: "latest"
  imagePullPolicy: "Always"
  imagePullSecret:
    - name: registry-secret
  resources:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 100Mi
  podsecurityContext:
    runAsUser: 1100
    runAsGroup: 1100
    fsGroup: 1100
    supplementalGroups: [1100]
  containersecurityContext:
    allowPrivilegeEscalation: false
    capabilities:
      drop:
        - ALL

data:
  redis_conf: |-

